### ISSUE TITLE
Error checking mirrored geogebra repo

### ISSUE THREAD

**Issue by algodelinux** [windtail/apt-mirror-check#2]
When I use apt-mirror-check, the tool shows this error processing geogebra repository:

 apt-mirror-check -b /var/spool/apt-mirror/
checking /var/spool/apt-mirror/mirror/es.archive.ubuntu.com/ubuntu/dists/bionic-proposed ...
checking /var/spool/apt-mirror/mirror/es.archive.ubuntu.com/ubuntu/dists/bionic ...
checking /var/spool/apt-mirror/mirror/es.archive.ubuntu.com/ubuntu/dists/bionic-backports ...
checking /var/spool/apt-mirror/mirror/es.archive.ubuntu.com/ubuntu/dists/bionic-updates ...
checking /var/spool/apt-mirror/mirror/security.ubuntu.com/ubuntu/dists/bionic-security ...
checking /var/spool/apt-mirror/mirror/archive.canonical.com/ubuntu/dists/bionic ...
checking /var/spool/apt-mirror/mirror/www.geogebra.net/linux/dists/stable ...
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/apt_mirror_check-1.0.2-py3.9.egg/apt_mirror_check.py", line 146, in bad_files_in_mirror
StopIteration

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/bin/apt-mirror-check", line 33, in <module>
    sys.exit(load_entry_point('apt-mirror-check==1.0.2', 'console_scripts', 'apt-mirror-check')())
  File "/usr/local/lib/python3.9/dist-packages/click-8.1.3-py3.9.egg/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/click-8.1.3-py3.9.egg/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.9/dist-packages/click-8.1.3-py3.9.egg/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.9/dist-packages/click-8.1.3-py3.9.egg/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/apt_mirror_check-1.0.2-py3.9.egg/apt_mirror_check.py", line 201, in cli
RuntimeError: generator raised StopIteration

**Comment by windtail** [comment]
Sorry for late reply. 

It seems the directory structure is unexpected. Some `dists` directory is empty. The geogebra mirror is ok, the bad mirror should be next mirror after geogebra.

**Comment by algodelinux** [comment]
Thanks you very much!
After a while, I wrote a bash script to check only the new packages downloaded by apt-mirror.

**Comment by windtail** [comment]
That's a good idea!
